# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish McPatch.csproj -o build\ -c Release -p:PublishTrimmed=true -p:PublishSingleFile=true -p:SelfContained=true -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=true
    - name: Upload publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: upload
        path: build
    - name: Test
      run: dotnet test --no-build --verbosity normal
